version: 2
jobs:
  selenium:
    docker:
      - image: circleci/openjdk:8-jdk-browsers
    steps:
      - checkout

      - run: java -version

      - run:
          name: Download Selenium
          command: curl -O http://selenium-release.storage.googleapis.com/3.5/selenium-server-standalone-3.5.3.jar
          
      - run:
          name: Start Selenium
          command: java -jar selenium-server-standalone-3.5.3.jar
          background: true
  mongodb:
    docker:
      - image: circleci/mongo:3.4.20
    steps:
      - checkout  
  test:
    docker:
      - image: circleci/node:11.13.0
    steps:
      - checkout

      - run: npm start selenium

      
      - run: npm install

      - run: npm run test:e2e    

workflows:
  version: 2
  build_and_test:
    jobs:
      - selenium
      - mongodb
      - test:
          requires:
            - selenium
            - mongodb

