version: 2
jobs:
  build:
    docker:
      - image: klamping/wdio-ff

    environment:
      GIT_URL: "git@github.com:albert-kovacs/lending-app.git"
      BRANCH: "master"

    steps:
      - checkout

      - run: npm install

      - run:
          command: cd react/fixtures/dom && yarn start
          background: true

      # run tests!
      - run: npm run test:e2e

