version: 2
jobs:
  test:
    docker:
      - image: circleci/node:11.13.0
    steps:
      - checkout

      - run: npm start selenium

      
      - run: npm install

      - run: npm run test:e2e    

workflows:
  version: 2
  build_and_test:
    jobs:
      - test

