version: 2
jobs:
  build:
    docker:
      - image: klamping/wdio-ff

    steps:
      - checkout

      - run: npm install

      - run: npm run lint
      - run: npm run unit
      - run: npm run test:features
      - run: npm run test:visualregression
      - run: npm run test:e2e


