version: 2
jobs:
  build:
    docker:
      - image: circleci/node:11.13.0
      - image: circleci/mongo:3.4.20
      - image: circleci/node:7.10
      - image: selenium/hub
        name: hub
      - image: selenium/node-firefox
        environment:
          HUB_PORT_4444_TCP_ADDR: hub
          HUB_PORT_4444_TCP_PORT: 4444
      - image: circleci/openjdk:8-jdk
    
    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: npm run lint
      - run: npm run unit
      - run: npm run test:e2e